[package]
name = "navkit-rpkg-lib"
version = "1.1.0"
edition = "2021"
license = "Apache-2.0"
categories = ["game-development", "data-structures", "parser-implementations"]
description = "A C++ library that has functions to find needed resources from a NavKit scene file and extract resources."
repository = "https://github.com/glacier-modding/navkit-rpkg-lib"
readme = "README.md"

[lib]
name = "navkit_rpkg_lib"
crate-type = ["cdylib", "rlib"]

[badges.maintenance]
status = "actively-developed"

[dependencies]
rpkg-rs = "1.4.0"
itertools = { version = "0.15.0", features = [] }
anyhow = "1.0.95"
rayon = { version = "1.10.0", optional = true }
serde = { version = "1.0.194", optional = true, features = ["derive"] }
serde_json = { version = "1.0.138" }
serde-hex = { version = "0.1.0", optional = true }
serde-smile = "0.3.1"
glacier-texture = "2.2.0"
glacier-ini = "1.0.0"
glacier-base = "0.2.1"

[dependencies.glacier-commons]
git = "https://github.com/atampy25/glacier-commons"
features = ["serde", "specta", "rpkg-rs-1", "glacier-texture", "tonytools", "hash-list"]

[target.'cfg(windows)'.dependencies.glacier-commons]
git = "https://github.com/atampy25/glacier-commons"
features = ["serde", "specta", "rpkg-rs-1", "glacier-texture", "tonytools", "hash-list", "game-detection"]

[dependencies.glacier-formats]
git = "https://github.com/atampy25/glacier-formats"
features = ["material", "serde"]

[dependencies.reqwest]
version = "0.13.5"
features = ["json", "blocking"]

[features]
default = ["path-list", "serde"]
path-list = ["dep:rayon"]
serde = ["dep:serde", "dep:serde-hex"]

[dev-dependencies]
serde_json = "1.0.116"

[build-dependencies]
cbindgen = "0.29.4"
